<?php echo'<?xml version="1.0" encoding="iso-8859-1"?>'; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "DTD/xhtml1-transitional.dtd">
<!--
PasteBin - By OrkutPlus!
-->
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>PasteBin - By OrkutPlus!</title>
	<style type="text/css" media="screen">
	<!--
	@import url(http://www.orkutplus.net/pastebin/style-core.css);
	@import url(http://www.orkutplus.net/pastebin/style.css);
		-->
	</style>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head profile="http://gmpg.org/xfn/11">

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

	<title>Orkut Plus!  </title>
	
	<meta name="generator" content="WordPress abc" /> <!-- leave this for stats -->

	<link type="image/x-icon" rel="icon" href="http://jerry.oplus.googlepages.com/op-favicon.ico"/>
	<link type="image/x-icon" rel="shortcut icon" href="http://jerry.oplus.googlepages.com/op-favicon.ico"/>
	
	<link rel="alternate" type="application/rss+xml" title="RSS 2.0" href="http://www.orkutplus.net/feed" />
	<link rel="alternate" type="text/xml" title="RSS .92" href="http://www.orkutplus.net/feed/rss" />
	<link rel="alternate" type="application/atom+xml" title="Atom 0.3" href="http://www.orkutplus.net/feed/atom" />

	<link rel="pingback" href="http://www.orkutplus.net/blog/xmlrpc.php" />

	<meta name='AMEWP' content='1.8.5' />
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://www.orkutplus.net/blog/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://www.orkutplus.net/blog/wp-includes/wlwmanifest.xml" /> 

<!-- all in one seo pack 1.4.6.14 ob_start_detected [-1,-1] -->
<!-- /all in one seo pack -->
<style type="text/css">.broken_link, a.broken_link {
	text-decoration: line-through;
}</style><script type="text/javascript" charset="utf-8" src="http://w.sharethis.com/widget/?wp=abc&amp;publisher=3a7ea146-b6e3-4546-b05c-d7d635648272"></script>
<!-- Start Of Script Generated By WP-PageNavi 2.31 -->

<link rel="stylesheet" href="http://www.orkutplus.net/blog/wp-content/plugins/wp-pagenavi/pagenavi-css.css" type="text/css" media="screen" />
<!-- End Of Script Generated By WP-PageNavi 2.31 -->
</head>
<body>
	<div id="brcoming"><br />
		<p align="center"><font size="4.5" face="Arial" color="white">Brazillian OrkutPlus coming soon! | Brasil OrkutPlus em breve!</font></p>
	</div>
	<div id="header">
<div id="blogtitle">
	<a href="/"><img src="http://www.orkutplus.net/blog/wp-content/themes/op/images/orkutpluslogoqr7.gif" alt="Orkut Plus"></a>
</div>
		<div id="banner">
<form action="http://www.orkutplus.net/search.php" id="cse-search-box">
<div>
<input type="hidden" name="cx" value="007418682267555033411:h1tpc4mtzre" />
<input type="hidden" name="cof" value="FORID:11" />
<input type="hidden" name="ie" value="UTF-8" />

<input type="text" name="q" size="31" />
<input type="submit" name="sa" value="Search" />
</div>
</form>
<script type="text/javascript" src="http://www.google.com/coop/cse/brand?form=cse-search-box&lang=en"></script>
</div>

	<div id="navbar">
		<ul class="menu">
			<li class="page_item">
<li><a href="http://www.orkutplus.net">Home</a></li>
<li><a href="http://www.orkutplus.net/category/security">Security Tips</a></li>

<li><a href="http://www.orkutplus.net/category/userscripts">Userscripts</a></li>
<li><a href="http://www.orkutplus.net/category/orkut-apps">Orkut Apps</a></li>
<li><a href="http://www.orkutplus.net/category/hacks">Hacks</a></li>
<li><a href="http://www.orkutplus.net/category/orkut-softwares">Softwares</a></li>
<li><a href="http://www.orkutplus.net/2005/01/orkut-proxy.html">Proxy</a></li>
<li><a href="http://www.orkutplus.net/category/orkut-themes">Orkut Themes</a></li>
<li><a href="http://www.orkutplus.net/2006/03/scrap-all.html">Scrap All</a></li>
<li><a href="http://www.orkutplus.net/about">About</a></li>
<li><a href="http://www.orkutplus.net/contact">Contact</a></li>

<li><a href="http://www.orkutplus.net/subscribe">Subscribe</a></li>
		</ul>
</div>
	</div> <!-- end of #navbar -->
	</div><div id="page_container">
<div id="leftbar" class="fixheight">
<div class="left-rbroundbox">
	<div class="left-rbtop"><div></div></div>
		<div class="left-rbcontent">
<div class="textwidget"><div class="lolclassic">
<div class="loltitleclassic"><center>Recent Posts</center></div>
<div style="padding: 7px 4px 5px 8px; font-size: 11px; color: rgb(68, 68, 68); line-height: 1.4em;">
<ul>
<?php  
	foreach($page['recent'] as $idx=>$entry)
	{
		if ($entry['pid']==$pid)
			$cls=" class=\"highlight\"";
		else
			$cls="";
			
		echo "<li{$cls}><a href=\"{$entry['url']}\">";
		echo $entry['poster'];
		echo "</a><br/>{$entry['agefmt']}</li>\n";
	}

	echo "<li><a rel=\"nofollow\" href=\"http://www.orkutplus.net/pastebin\">Make New Post</a></li>";
?>
</ul></div></div></div><br/>
<div class="textwidget"><div class="lolclassic">
<div class="loltitleclassic"><center>About</center></div><div style="padding: 7px 4px 5px 8px; font-size: 11px; color: rgb(68, 68, 68); line-height: 1.4em;">
<p>
PasteBin is a Tool which allows you to Share and Modify Code Snippets! <a href="?help=1">See Help for Details</a>
</div></p></div></div><br/><div class="textwidget"><div class="lolclassic">
<?php
if (isset($page['thankyou']))
{
	echo '<div style="padding: 7px 4px 5px 8px; font-size: 11px; color: rgb(68, 68, 68); line-height: 1.4em;">';
	echo "<p style=\"color:red;\">{$page['thankyou']}</p></div>";
}
else
{
?>
<div class="loltitleclassic"><center>Please Send FeedBack:</center></div><div style="padding: 7px 4px 5px 8px; font-size: 11px; color: rgb(68, 68, 68); line-height: 1.4em;">
<form method="post" action="index.php#feedback">
<center><br><textarea name="msg" rows="5" style="width:80%;font-size:8pt;font-family:Arial;"></textarea><br><Br>
<input type="hidden" name="feedback" value="1"/></center>
<input style="width:90%;margin-left:5%" type="submit" value="Send FeedBack"/>
</form><br/></div>
<?php }
?>
</div></div>
<div class="left-rbbot"><div></div></div></div></div></div>
<div class="rbroundbox">
<div class="left-rbtop"><div></div></div>
<div class="rbcontent">
<div id="postcol" class="fixheight">
<?php if (isset($page['post']['codecss']))
{
	echo '<style type="text/css">';
	echo $page['post']['codecss'];
	echo '</style>';
}
?>
<script type="text/javascript" src="pastebin.js?ver=3"></script>
</head>
<body onload="initPastebin()">
<div class="post_title">
<h2 class="title"><a href="index.php">PasteBin</a></h2>
<p><small class="title">PasteBin is a Tool which allows you to Share and Modify Code Snippets while chatting on IRC, IM or a Message Board.</small></p>
<p><small class="title">In case you are facing any problem, we would advise you to go through the <a href="?help=1">Help and FAQ Section</a>.</small></p>
</div>
<div id="content">
<div style="padding: 7px 4px 5px 8px; font-size: 11px; color: rgb(68, 68, 68); line-height: 1.4em;">
<?php
/*
<?php
if (strlen($CONF['google_ad_client'])) 
{
?>
<script type="text/javascript"><!--
google_ad_client = "<?php echo $CONF['google_ad_client'] ?>";
google_ad_width = 728;
google_ad_height = 90;
google_ad_format = "728x90_as";
google_ad_type = "text_image";
google_ad_channel ="";
google_color_border = "FFFFFF";
google_color_bg = "FFFFFF";
google_color_link = "474C7F";
google_color_url = "888888";
google_color_text = "000000";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
<br/>
<br/>
<?php
}
*/
if (count($pastebin->errors))
{
	echo 'Errors<br><ul>';
	foreach($pastebin->errors as $err)
	{
		echo "<li>$err</li>";
	}
	echo "</ul>";
	echo "<hr />";
}
if (!empty($page['delete_message']))
{
	echo $page['delete_message']."<br/>";
}
if (isset($_REQUEST["diff"]))
{
	$newpid=$pastebin->cleanPostId($_REQUEST['diff']);
	$newpost=$pastebin->getPost($newpid);
	if (count($newpost))
	{
		$oldpost=$pastebin->getPost($newpost['parent_pid']);
		if (count($oldpost))
		{
			$page['pid']=$newpid;
			$page['current_format']=$newpost['format'];
			$page['editcode']=$newpost['code'];
			$page['posttitle']='';
			echo '<br>Difference Between Modified Post and Original Post.<br>'.$newpost["poster"].' Posted On '.$newpost["postdate"].'. Link: <a href="'.$pastebin->getPostUrl($oldpost["pid"]).'">'.$oldpost["pid"].'</a><br>'.$oldpost["poster"].' Posted On '.$oldpost["postdate"].'. Link: <a href="'.$pastebin->getPostUrl($newpost["pid"]).'">'.$newpost["pid"].'</a><br><br/>';
			/*
			echo "Show: ";
			echo " <a title=\"Don't Show Inserted or Changed Lines\" style=\"padding:1px 4px 3px 4px;\" id=\"oldlink\" href=\"javascript:showold()\">Old Version</a> | ";
			echo "<a title=\"Don't Show Lines Removed from Old Version\" style=\"padding:1px 4px 3px 4px;\" id=\"newlink\" href=\"javascript:shownew()\">New Version</a> | ";
			echo "<a title=\"Show Both Insertions and Deletions\" style=\"background:#880000;padding:1px 4px 3px 4px;\" id=\"bothlink\" href=\"javascript:showboth()\">Both Versions</a> ";
			*/
			$newpost['code']=preg_replace('/^'.$CONF['highlight_prefix'].'/m', '', $newpost['code']);
			$oldpost['code']=preg_replace('/^'.$CONF['highlight_prefix'].'/m', '', $oldpost['code']);
			$a1=explode("\n", $newpost['code']);
			$a2=explode("\n", $oldpost['code']);
			$diff=new Diff($a2,$a1, 1);
			echo "<table cellpadding=\"0\" cellspacing=\"0\" class=\"diff\">";
			echo "<tr><td></td><td></td><td>&nbsp;&nbsp;&nbsp;&nbsp;</td><td></td></tr>";
			echo $diff->output;
			echo "</table>";
		}		
	}
}
if (isset($_GET['help']))
	$page['posttitle']="";
if (strlen($page['post']['posttitle']))
{
		echo $page['post']['posttitle'];
		if (strlen($page['post']['parent_pid']))
		{
			echo ' (';
			echo 'Modification of Post by ';
			echo "<a href='{$page['post']['parent_url']}' title='View Original Post'>{$page['post']['parent_poster']}</a>)<br>";
			echo "<a href=\"{$page['post']['parent_diffurl']}\" title=\"Compare Differences\">View Difference</a>";
		if (strlen($page['post']['token']) && ($page['token']==$page['post']['token']))
		{
			echo " | <a href=\"{$page['post']['deleteurl']}\" title=\"Delete Post\">Delete Post</a> | ";
		}
		}
		$followups=count($page['post']['followups']);
		if ($followups)
		{
			echo '<br>View followups from ';
			$sep="";
			foreach($page['post']['followups'] as $idx=>$followup)
			{
				echo $sep."<a title=\"posted {$followup['postfmt']}\" href=\"{$followup['followup_url']}\">{$followup['poster']}</a>";
				$sep=($idx<($followups-2))?", ":(' and ');	
			}
			
			echo "<br>";
		}
		
		if ($page['post']['parent_pid']>0)
		{
			echo "<a href=\"{$page['post']['parent_diffurl']}\" title=\"compare differences\">View Difference</a>";
		}
		echo " | <a href=\"{$page['post']['downloadurl']}\" title=\"Download File\">Download</a> | <a rel=\"nofollow\" href=\"http://www.orkutplus.net/pastebin\">Make New Post</a>";
}
if (isset($page['post']['pid']))
{
	echo "<div class=\"syntax\">".$page['post']['codefmt']."</div>";
	echo "<br /><b>Submit a Correction or Amendment Below. (<a href=\"{$CONF['this_script']}\">Click Here to Make a Fresh Posting!</a>)</b><br/>";
	echo 'After Submitting an Amendment, You will be Able to View the Differences between the Old and New Posts Easily!';
}	
if (isset($_GET['help']))
{
	?><br><br><div class="loltitleclassic">What is PasteBin?</div>
	<p>PasteBin is a Tool which allows you to Share and Modify Code Snippets! If you're not Familiar with the Idea, Most People use it like this:</p>	
	<ul>
	<li>They <a href="?">Submit</a> a Code Fragment to PasteBin, They Get a url like http://orkutplus.net/pastebin/?show=1</li>
	<li>They Send the Code to their Friends.</li>
	<li>People make Modifications to the Code and Post a new Code.</li>
	<li>They then view the Modifications.</li>
	</ul>
	<div class="loltitleclassic">How can I View the Differences between 2 Posts?</div>
	
	<p>When you view a Post, You have the Opportunity of Editing the Text - <strong>This creates a new Post</strong>, But when you view it, You'll be given different link which Allows you to Compare the Changes between the Old and the New Version</p>
	<p>This is a Powerful Feature, Great for Seeing Exactly what Lines Someone Changed!</p>	
	<div class="loltitleclassic">How can I delete a Post?</div>
	<p>If you clicked the "Remember Me" checkbox while posting, You will be able to Delete the Post from the Same Computer you Posted from - Simply view the Post and Click the "Delete Post" link. We use Cookies for this Method, if You have those Cookies, You will be able to Delete the Post.</p>
	<?php } ?>
<form name="editor" method="post">
<input type="hidden" name="parent_pid" value="<?php echo $page['post']['pid'] ?>"/>
<br/>Syntax highlighting:&nbsp;&nbsp;<select name="format"> 
<?php
foreach ($CONF['all_syntax'] as $code=>$name)
{
	if (in_array($code, $CONF['popular_syntax']))
	{
		$sel=($code==$page['current_format'])?"selected=\"selected\"":"";
		echo "<option $sel value=\"$code\">$name</option>";
	}
}
echo "<option value=\"text\">----------------------------</option>";
foreach ($CONF['all_syntax'] as $code=>$name)
{
	$sel=($code==$page['current_format'])?"selected=\"selected\"":"";
	if (in_array($code, $CONF['popular_syntax']))
		$sel="";
	echo "<option $sel value=\"$code\">$name</option>";
	
}
?>
</select><br/>
<br/>

To highlight particular lines, prefix each line with @@
<br/>
<textarea id="code" class="codeedit" name="code2" cols="80" rows="10" onkeydown="return catchTab(this,event)"><?php 
echo htmlentities($page['post']['editcode'], ENT_COMPAT,$CONF['htmlentity_encoding']) ?></textarea><br>	
<p>Your Name:&nbsp;&nbsp;<input type="text" maxlength="24" size="24" id="poster" name="poster" value="<?php echo $page['poster'] ?>" /></p>
<p>
<?php echo '<input type="checkbox" name="remember" value="1" '.$page['remember'].' />&nbsp;Remember Me'; ?></p>
<p>How long should your Post be Retained?<br>
<input type="radio" id="expiry_day" name="expiry" value="d" <?php if ($page['expiry']=='d') echo 'checked="checked"'; ?> />
A Day

<input type="radio" id="expiry_month" name="expiry" value="m" <?php if ($page['expiry']=='m') echo 'checked="checked"'; ?> />
A Month

<input type="radio" id="expiry_forever" name="expiry" value="f" <?php if ($page['expiry']=='f') echo 'checked="checked"'; ?> />
Forever</p><p>
<input type="submit" name="paste" value="Submit"/></p>
</form>
<div style="clear: both"></div></div></div>
</div></div><!-- /rbcontent -->
<div class="rbbot"><div></div></div>
</div><!-- /rbroundbox -->
</div> <!-- close page container-->

</body>
</html>