// ==UserScript==
// @name	All emotions by Dhawal
// @version	1.00
// @author	Dhawal
// @namespace	TEAM BLAKUT
// @description	Use Animated smileys in your ScrapBook and HTML community Forums. Just click on a smiley to insert. Enjoy
// @include        http://*.orkut.*/*Scrapbook.aspx*
// @include        http://*.orkut.*/*CommMsgs.aspx*
// @include        http://*.orkut.*/*CommMsgPost.aspx*
// ==/UserScript==

/**********************************************************************************************************************************************************
//Script Template by Swashata [Team Blakut]
//Original Base script by Fenil
***********************************************************************************************************************************************************/

addEventListener('load', function(event) {
function getTextArea(n) {
	return document.getElementsByTagName('textarea')[n];
}


function insertSmiley(){
	var image = this.getElementsByTagName('img')[0].getAttribute("src");
	getTextArea(this.getAttribute("gult")).focus();
	getTextArea(this.getAttribute("gult")).value += "<img src="+image+">";
}

function dip() {
	var smileyarr = new Array();	
//COPY PASTE THE CODES GENERATED BY THE SCRIPT HELPER BELOW THIS LINE	

smileyarr["102"]="http://lh3.ggpht.com/_Nhh98Ix90W8/ScHmzXK0vOI/AAAAAAAAAGY/bYJQsq4e-8M/102.gif";
smileyarr["101"]="http://lh5.ggpht.com/_Nhh98Ix90W8/ScHmz53YnnI/AAAAAAAAAGc/xa7v-VhjKDc/101.gif";
smileyarr["100"]="http://lh3.ggpht.com/_Nhh98Ix90W8/ScHm0rWf3HI/AAAAAAAAAGg/fot4FFHGUAY/100.gif";
smileyarr["099"]="http://lh4.ggpht.com/_Nhh98Ix90W8/ScHm1Di21RI/AAAAAAAAAGk/8ino7ByHsYM/099.gif";
smileyarr["098"]="http://lh3.ggpht.com/_Nhh98Ix90W8/ScHm1qyT7pI/AAAAAAAAAGo/DAteGKkLFZQ/098.gif";
smileyarr["097"]="http://lh4.ggpht.com/_Nhh98Ix90W8/ScHm2UqlfpI/AAAAAAAAAGs/LbNxG3R9rac/097.gif";
smileyarr["096"]="http://lh5.ggpht.com/_Nhh98Ix90W8/ScHm20rA5fI/AAAAAAAAAGw/cDuOSBu4FkI/096.gif";
smileyarr["095"]="http://lh3.ggpht.com/_Nhh98Ix90W8/ScHm3qIveOI/AAAAAAAAAG0/4SkpLekzKcg/095.gif";
smileyarr["094"]="http://lh5.ggpht.com/_Nhh98Ix90W8/ScHm4O9rhZI/AAAAAAAAAG4/m_reDn30VzU/094.gif";
smileyarr["093"]="http://lh5.ggpht.com/_Nhh98Ix90W8/ScHm5P5jn5I/AAAAAAAAAG8/QIlD93P61bk/093.gif";
smileyarr["092"]="http://lh6.ggpht.com/_Nhh98Ix90W8/ScHm58zVz1I/AAAAAAAAAHA/VgguMe-Ebhk/092.gif";
smileyarr["091"]="http://lh4.ggpht.com/_Nhh98Ix90W8/ScHm6drt34I/AAAAAAAAAHE/rY1IKjr5tik/091.gif";
smileyarr["090"]="http://lh3.ggpht.com/_Nhh98Ix90W8/ScHm7EGZiPI/AAAAAAAAAHI/qq-gCmb6fL0/090.gif";
smileyarr["089"]="http://lh3.ggpht.com/_Nhh98Ix90W8/ScHm7gWzpSI/AAAAAAAAAHM/cSbHq6SdvbU/089.gif";
smileyarr["088"]="http://lh4.ggpht.com/_Nhh98Ix90W8/ScHm8FZu10I/AAAAAAAAAHQ/YKqTGy8m0M8/088.gif";
smileyarr["087"]="http://lh3.ggpht.com/_Nhh98Ix90W8/ScHm8nd3hTI/AAAAAAAAAHU/9L4GulTMdEc/087.gif";
smileyarr["086"]="http://lh3.ggpht.com/_Nhh98Ix90W8/ScHm9ODVyEI/AAAAAAAAAHY/62hd-YbqKvE/086.gif";
smileyarr["085"]="http://lh3.ggpht.com/_Nhh98Ix90W8/ScHm9kDnFII/AAAAAAAAAHc/FE7Lby4blE8/085.gif";
smileyarr["084"]="http://lh4.ggpht.com/_Nhh98Ix90W8/ScHm-MrOwQI/AAAAAAAAAHg/5WPcUesx_wU/084.gif";
smileyarr["083"]="http://lh5.ggpht.com/_Nhh98Ix90W8/ScHm-qqtSrI/AAAAAAAAAHk/g3KxSHuwm88/083.gif";
smileyarr["082"]="http://lh4.ggpht.com/_Nhh98Ix90W8/ScHm_T_t9tI/AAAAAAAAAHo/Z77mWsCDntI/082.gif";
smileyarr["081"]="http://lh3.ggpht.com/_Nhh98Ix90W8/ScHm_8bC4KI/AAAAAAAAAHs/9v7YAOakO1M/081.gif";
smileyarr["080"]="http://lh5.ggpht.com/_Nhh98Ix90W8/ScHnAeFeuGI/AAAAAAAAAHw/bGC6a5cqW_s/080.gif";
smileyarr["079"]="http://lh3.ggpht.com/_Nhh98Ix90W8/ScHnAzaGoRI/AAAAAAAAAH0/h6UTpdcJfUE/079.gif";
smileyarr["078"]="http://lh5.ggpht.com/_Nhh98Ix90W8/ScHnBcKS4PI/AAAAAAAAAH4/QbHSu0LWiO4/078.gif";
smileyarr["077"]="http://lh4.ggpht.com/_Nhh98Ix90W8/ScHnBr0UVPI/AAAAAAAAAH8/1nnpgD3_vdw/077.gif";
smileyarr["076"]="http://lh6.ggpht.com/_Nhh98Ix90W8/ScHnCpeCtkI/AAAAAAAAAIA/mXfL9Vcv2EE/076.gif";
smileyarr["075"]="http://lh5.ggpht.com/_Nhh98Ix90W8/ScHnDGfrgTI/AAAAAAAAAIE/B4tH3HC7x4w/075.gif";
smileyarr["074"]="http://lh3.ggpht.com/_Nhh98Ix90W8/ScHnDWHkeWI/AAAAAAAAAII/3fwlsjTD8j8/074.gif";
smileyarr["073"]="http://lh6.ggpht.com/_Nhh98Ix90W8/ScHnEHhMRhI/AAAAAAAAAIM/BhCWdT-DFxY/073.gif";
smileyarr["072"]="http://lh5.ggpht.com/_Nhh98Ix90W8/ScHnE5DkdnI/AAAAAAAAAIQ/8U0qnyR9JVk/072.gif";
smileyarr["071"]="http://lh4.ggpht.com/_Nhh98Ix90W8/ScHnFJq2KCI/AAAAAAAAAIU/maxLZ5PCg-c/071.gif";
smileyarr["070"]="http://lh3.ggpht.com/_Nhh98Ix90W8/ScHnFq67xrI/AAAAAAAAAIY/hC42ltqXM3g/070.gif";
smileyarr["069"]="http://lh6.ggpht.com/_Nhh98Ix90W8/ScHnGFxA9bI/AAAAAAAAAIc/PeF5sLhNOZA/069.gif";
smileyarr["068"]="http://lh5.ggpht.com/_Nhh98Ix90W8/ScHnGoxpiUI/AAAAAAAAAIg/6S4YTGE-9Ls/068.gif";
smileyarr["067"]="http://lh5.ggpht.com/_Nhh98Ix90W8/ScHnHG5DuRI/AAAAAAAAAIk/ZKUTwwBO5Ik/067.gif";
smileyarr["066"]="http://lh4.ggpht.com/_Nhh98Ix90W8/ScHnHq14CmI/AAAAAAAAAIo/KRmKiZ0wgeI/066.gif";
smileyarr["065"]="http://lh6.ggpht.com/_Nhh98Ix90W8/ScHnIDAEZBI/AAAAAAAAAIs/55Bf43ApV44/065.gif";
smileyarr["064"]="http://lh5.ggpht.com/_Nhh98Ix90W8/ScHnIhkhTPI/AAAAAAAAAIw/XXRHOZqMzfM/064.gif";
smileyarr["063"]="http://lh5.ggpht.com/_Nhh98Ix90W8/ScHnJIOX8eI/AAAAAAAAAI0/VC2AD9K6z04/063.gif";
smileyarr["062"]="http://lh3.ggpht.com/_Nhh98Ix90W8/ScHnJutLM4I/AAAAAAAAAI4/51Fg61vlYi8/062.gif";
smileyarr["061"]="http://lh3.ggpht.com/_Nhh98Ix90W8/ScHnKAYxXvI/AAAAAAAAAI8/WsMP4XvaFzg/061.gif";
smileyarr["060"]="http://lh5.ggpht.com/_Nhh98Ix90W8/ScHnKoNR9-I/AAAAAAAAAJA/sDAgDTtkg5U/060.gif";
smileyarr["059"]="http://lh3.ggpht.com/_Nhh98Ix90W8/ScHnLNQlCWI/AAAAAAAAAJE/P49xKmuPAWI/059.gif";
smileyarr["058"]="http://lh4.ggpht.com/_Nhh98Ix90W8/ScHnLpswhII/AAAAAAAAAJI/f3Ih-hVPQZQ/058.gif";
smileyarr["057"]="http://lh6.ggpht.com/_Nhh98Ix90W8/ScHnMXjnuBI/AAAAAAAAAJM/E6f8D8rzHOo/057.gif";
smileyarr["056"]="http://lh3.ggpht.com/_Nhh98Ix90W8/ScHnMxx6-DI/AAAAAAAAAJQ/RPr2X3GGVS4/056.gif";
smileyarr["055"]="http://lh5.ggpht.com/_Nhh98Ix90W8/ScHnNbdKdVI/AAAAAAAAAJU/5fVrWQbs-GI/055.gif";

	

//DO NOT CHANGE ANY THING BELOW THIS LINE
	var tb = document.getElementsByTagName('textarea');
	for(i=0;i<tb.length;i++){
		text=tb[i];
		if (!text) return;
		c=text.parentNode;
		d=document.createElement("div");
		d.className="T";
		d.style.fontSize="11px";
		d.align="left";
		
	        
	    d.style.marginTop="10px";
		c.appendChild(d);
		
		for(title in smileyarr){
			mm=document.createElement("a");
			mm.href="javascript:;";
			mm.setAttribute("gult",i);
			mm.innerHTML="<img src='"+smileyarr[title]+"' title='"+title+"'>";
			mm.addEventListener("click", insertSmiley, true);
			d.appendChild(mm);
		}
	}	
}
dip();
}, false);

//More Smileys could be found on http://www.blakut.com/2008/12/use-animated-smileys-to-make-orkutting.html
// Visit our official website www.blakut.com for regualr update on smileys and other orkut related stuffs.
//~~Happy Orkutting~~
// Regards--- Swashata