// ==UserScript==
// @name	Black Smiles by Dhawal
// @version	1.00
// @author	Dhawal
// @namespace	TEAM BLAKUT
// @description	Use Animated smileys in your ScrapBook and HTML community Forums. Just click on a smiley to insert. Enjoy
// @include        http://*.orkut.*/*Scrapbook.aspx*
// @include        http://*.orkut.*/*CommMsgs.aspx*
// @include        http://*.orkut.*/*CommMsgPost.aspx*
// ==/UserScript==

/**********************************************************************************************************************************************************
//Script Template by Swashata [Team Blakut]
//Original Base script by Fenil
***********************************************************************************************************************************************************/

addEventListener('load', function(event) {
function getTextArea(n) {
	return document.getElementsByTagName('textarea')[n];
}


function insertSmiley(){
	var image = this.getElementsByTagName('img')[0].getAttribute("src");
	getTextArea(this.getAttribute("gult")).focus();
	getTextArea(this.getAttribute("gult")).value += "<img src="+image+">";
}

function dip() {
	var smileyarr = new Array();	
//COPY PASTE THE CODES GENERATED BY THE SCRIPT HELPER BELOW THIS LINE	

smileyarr["big_smile"]="http://lh6.ggpht.com/_Nhh98Ix90W8/ScEqJPxov5I/AAAAAAAAADg/uQksbJkHPWQ/big_smile.gif";
smileyarr["confused"]="http://lh4.ggpht.com/_Nhh98Ix90W8/ScEqJXZp9rI/AAAAAAAAADo/nboRYp2SzPk/confused.gif";
smileyarr["Cry"]="http://lh3.ggpht.com/_Nhh98Ix90W8/ScEqJhuTKVI/AAAAAAAAADw/kfkr0jDIG5c/Cry.gif";
smileyarr["Dag"]="http://lh4.ggpht.com/_Nhh98Ix90W8/ScEqJor4zLI/AAAAAAAAAD4/cg4X31voRQ8/Dag.gif";
smileyarr["Girl"]="http://lh5.ggpht.com/_Nhh98Ix90W8/ScEqKDavLQI/AAAAAAAAAEA/yocBCKLHueo/Girl.gif";
smileyarr["Haha"]="http://lh6.ggpht.com/_Nhh98Ix90W8/ScEqXNFsBYI/AAAAAAAAAEI/YF4bsGZxC0U/Haha.gif";
smileyarr["Shy"]="http://lh6.ggpht.com/_Nhh98Ix90W8/ScEqXSbD4kI/AAAAAAAAAEQ/hDna5hYgNFA/Shy.gif";
smileyarr["Sunglasses"]="http://lh6.ggpht.com/_Nhh98Ix90W8/ScEqXQhrHfI/AAAAAAAAAEY/-24-MCnTWQ8/Sunglasses.gif";
smileyarr["unhappy"]="http://lh5.ggpht.com/_Nhh98Ix90W8/ScEqXonZP4I/AAAAAAAAAEg/Zu9y4BFn020/unhappy.gif";
smileyarr["vlieg"]="http://lh4.ggpht.com/_Nhh98Ix90W8/ScEqXumgt3I/AAAAAAAAAEo/fbhyz5oHUrQ/vlieg.gif";
smileyarr["What_The"]="http://lh3.ggpht.com/_Nhh98Ix90W8/ScEqgX944II/AAAAAAAAAEw/lvFTHpP6-JQ/What_The.gif";
	

//DO NOT CHANGE ANY THING BELOW THIS LINE
	var tb = document.getElementsByTagName('textarea');
	for(i=0;i<tb.length;i++){
		text=tb[i];
		if (!text) return;
		c=text.parentNode;
		d=document.createElement("div");
		d.className="T";
		d.style.fontSize="11px";
		d.align="left";
		
	        
	    d.style.marginTop="10px";
		c.appendChild(d);
		
		for(title in smileyarr){
			mm=document.createElement("a");
			mm.href="javascript:;";
			mm.setAttribute("gult",i);
			mm.innerHTML="<img src='"+smileyarr[title]+"' title='"+title+"'>";
			mm.addEventListener("click", insertSmiley, true);
			d.appendChild(mm);
		}
	}	
}
dip();
}, false);

//More Smileys could be found on http://www.blakut.com/2008/12/use-animated-smileys-to-make-orkutting.html
// Visit our official website www.blakut.com for regualr update on smileys and other orkut related stuffs.
//~~Happy Orkutting~~
// Regards--- Swashata